services:
  - type: web
    name: netflix-cookie-checker
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: CHAT_ID
        sync: false
      - key: NODE_VERSION
        value: "20"
